// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5Z3g1Mpt1y7KsPLHowmWmWwW73pnn9k',
    appId: '1:651351206557:web:7565ff2e20876787e7c274',
    messagingSenderId: '651351206557',
    projectId: 'linklly-9525b',
    authDomain: 'linklly-9525b.firebaseapp.com',
    storageBucket: 'linklly-9525b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5Z3g1Mpt1y7KsPLHowmWmWwW73pnn9k',
    appId: '1:651351206557:android:e46d57c1eba53e05e7c274', // Updated to match Firebase Console
    messagingSenderId: '651351206557',
    projectId: 'linklly-9525b',
    storageBucket: 'linklly-9525b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArcjgyMHQltdKobmGwhth3W31soxNOKto',
    appId: '1:651351206557:ios:60642554beb84a0ee7c274',
    messagingSenderId: '651351206557',
    projectId: 'linklly-9525b',
    storageBucket: 'linklly-9525b.firebasestorage.app',
    iosBundleId: 'com.vynco.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArcjgyMHQltdKobmGwhth3W31soxNOKto',
    appId: '1:651351206557:ios:60642554beb84a0ee7c274',
    messagingSenderId: '651351206557',
    projectId: 'linklly-9525b',
    storageBucket: 'linklly-9525b.firebasestorage.app',
    iosBundleId: 'com.vynco.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi5Z3g1Mpt1y7KsPLHowmWmWwW73pnn9k',
    appId: '1:651351206557:web:7565ff2e20876787e7c274',
    messagingSenderId: '651351206557',
    projectId: 'linklly-9525b',
    storageBucket: 'linklly-9525b.firebasestorage.app',
  );
}
